apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aiops-app-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: aiops-app-dev
    app.kubernetes.io/part-of: aiops-platform
    aiops.dev/environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/truong-devops/aiops-gitops-manifests.git
    targetRevision: main
    path: environments/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
