apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aiops-observability
  namespace: argocd
  labels:
    app.kubernetes.io/name: aiops-observability
    app.kubernetes.io/part-of: aiops-platform
spec:
  project: default
  source:
    repoURL: https://github.com/truong-devops/aiops-gitops-manifests.git
    targetRevision: main
    path: platform/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
